// <auto-generated />
using System;
using IntegradorSofttekImanol.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilleteraVirtualSofttekBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231026062050_53463463")]
    partial class _53463463
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("account_balance");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("account_type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("account");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseAccount");
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_email");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("client_role");

                    b.HasKey("Id");

                    b.ToTable("client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 498, DateTimeKind.Local).AddTicks(1219),
                            Email = "1@1.com",
                            Name = "random",
                            Password = "389aec82d3ce947fd1ba75e52b2b49d5e7ffcebe7d8e059db3bb8c49594d0bbf",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 498, DateTimeKind.Local).AddTicks(1283),
                            Email = "2@2.com",
                            Name = "random",
                            Password = "389aec82d3ce947fd1ba75e52b2b49d5e7ffcebe7d8e059db3bb8c49594d0bbf",
                            Role = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 498, DateTimeKind.Local).AddTicks(1438),
                            Email = "3@3.com",
                            Name = "random",
                            Password = "389aec82d3ce947fd1ba75e52b2b49d5e7ffcebe7d8e059db3bb8c49594d0bbf",
                            Role = 2
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("transaction_amount");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_client");

                    b.Property<int>("Concept")
                        .HasColumnType("int")
                        .HasColumnName("transaction_concept");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<int>("DestinationAccountId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_destination_account");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date");

                    b.Property<int>("SourceAccountId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_source_account");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("SourceAccountId");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Accounts.CryptoAccount", b =>
                {
                    b.HasBaseType("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("accound_uuid");

                    b.ToTable("account");

                    b.HasDiscriminator().HasValue("CryptoAccount");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Balance = 1000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 501, DateTimeKind.Local).AddTicks(9199),
                            Type = 3,
                            UUID = new Guid("f88ea603-6b06-4c3d-a7e9-3dd20ca654fd")
                        },
                        new
                        {
                            Id = 6,
                            Balance = 2000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 501, DateTimeKind.Local).AddTicks(9204),
                            Type = 3,
                            UUID = new Guid("e972d390-cd4a-4702-8713-2506959ad138")
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Accounts.DollarAccount", b =>
                {
                    b.HasBaseType("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount");

                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("account_number");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_alias");

                    b.Property<int>("CBU")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("account_cbu");

                    b.ToTable("account");

                    b.HasDiscriminator().HasValue("DollarAccount");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Balance = 2000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 500, DateTimeKind.Local).AddTicks(9349),
                            Type = 2,
                            AccountNumber = 2,
                            Alias = "Trial.Hamen.Ryu",
                            CBU = 234567891
                        },
                        new
                        {
                            Id = 5,
                            Balance = 0m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 500, DateTimeKind.Local).AddTicks(9353),
                            Type = 2,
                            AccountNumber = 56564345,
                            Alias = "Accordion.Lupin.Extract",
                            CBU = 654334523
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Accounts.PesoAccount", b =>
                {
                    b.HasBaseType("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount");

                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("account_number");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("account_alias");

                    b.Property<int>("CBU")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int")
                        .HasColumnName("account_cbu");

                    b.ToTable("account");

                    b.HasDiscriminator().HasValue("PesoAccount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 499, DateTimeKind.Local).AddTicks(6937),
                            Type = 1,
                            AccountNumber = 134567544,
                            Alias = "Rock.Spy.Pink",
                            CBU = 123456789
                        },
                        new
                        {
                            Id = 4,
                            Balance = 2000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 26, 3, 20, 49, 499, DateTimeKind.Local).AddTicks(6941),
                            Type = 1,
                            AccountNumber = 434567346,
                            Alias = "Sword.Javelin.Coconut",
                            CBU = 532456234
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount", b =>
                {
                    b.HasOne("BilleteraVirtualSofttekBack.Models.Entities.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Transaction", b =>
                {
                    b.HasOne("BilleteraVirtualSofttekBack.Models.Entities.Client", "Client")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount", "DestinationAccount")
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount", "SourceAccount")
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DestinationAccount");

                    b.Navigation("SourceAccount");
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Client", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
