// <auto-generated />
using System;
using IntegradorSofttekImanol.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilleteraVirtualSofttekBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231018161549_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("account_money");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseAccount");
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 13, 15, 49, 142, DateTimeKind.Local).AddTicks(4587),
                            Email = "1@1.com",
                            Name = "random",
                            Password = "389aec82d3ce947fd1ba75e52b2b49d5e7ffcebe7d8e059db3bb8c49594d0bbf"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 18, 13, 15, 49, 142, DateTimeKind.Local).AddTicks(4714),
                            Email = "2@2.com",
                            Name = "random",
                            Password = "389aec82d3ce947fd1ba75e52b2b49d5e7ffcebe7d8e059db3bb8c49594d0bbf"
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Accounts.CryptoAccount", b =>
                {
                    b.HasBaseType("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("Accounts");

                    b.HasDiscriminator().HasValue("CryptoAccount");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Balance = 1000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 13, 15, 49, 145, DateTimeKind.Local).AddTicks(9984),
                            Type = 3,
                            UUID = new Guid("c2822a8e-e702-40b6-be2e-b2eb9a176b91")
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Accounts.DollarAccount", b =>
                {
                    b.HasBaseType("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount");

                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CBU")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.ToTable("Accounts");

                    b.HasDiscriminator().HasValue("DollarAccount");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Balance = 2000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 13, 15, 49, 145, DateTimeKind.Local).AddTicks(210),
                            Type = 2,
                            AccountNumber = 2,
                            Alias = "roca",
                            CBU = 234567891
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Accounts.PesoAccount", b =>
                {
                    b.HasBaseType("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount");

                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CBU")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("int");

                    b.ToTable("Accounts");

                    b.HasDiscriminator().HasValue("PesoAccount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000m,
                            ClientId = 1,
                            CreatedDate = new DateTime(2023, 10, 18, 13, 15, 49, 143, DateTimeKind.Local).AddTicks(7874),
                            Type = 1,
                            AccountNumber = 1,
                            Alias = "espada",
                            CBU = 123456789
                        });
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.BaseAccount", b =>
                {
                    b.HasOne("BilleteraVirtualSofttekBack.Models.Entities.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BilleteraVirtualSofttekBack.Models.Entities.Client", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
